platform :ios, '8.0'
target 'DrDriver' do
    pod 'Masonry', '~> 1.1.0'
    pod 'MJExtension', '~> 3.2.1'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'MJRefresh', '~> 3.2.2'
    pod 'AFNetworking', '~> 3.2.1'
    pod 'SDWebImage', '~> 5.3.1'
    pod 'SVProgressHUD', '~> 2.2.5'
    pod 'TencentOpenApiSDK', '~> 2.9.5'
    pod 'AMap3DMap', '~> 7.1.0'
    pod 'AMapSearch', '~> 7.1.0'
    pod 'AMapLocation', '~> 2.6.3'
    pod 'AMapNavi', '~> 7.1.0'
    pod 'JPush', '~> 3.2.6'
    pod 'AlipaySDK-iOS',  '~> 15.7.4'
end
